export interface Produtos{
    id: number,
    categoriaId: string,
    nome: "",
    shortName: "" ,
    descricao:"" ,
    descricaoAvancada: "",
    preco: number,
    produtoSazonal: "",
    imgUrl: "",
    createdAt: Date,
    updatedAt: Date,
    isComposto: "",
    precoDesconto: "",
    dataPromocao: "",
    isPromocao: "",
    isSazonal: "",
    order: "",
    produtoAtivo: boolean,
    codigoBarras: "",
    ncm: "",
    cfop: "",
    extipi: "",
    cest: "",
    cEnqIPI: "",
    pFCP: "",
    idParametroTributacao: number,
    parametroTributacao: "",
    categoria: "",
    comboProdutocompostos: [],
    produtopedidos: [],
    items: ""
}